quarkus.application.name= example-quarkus
quarkus.http.port=8181

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/mydatabase
quarkus.datasource.username=postgres
quarkus.datasource.password=password

quarkus.hibernate-orm.log.format-sql=true
quarkus.datasource.devservices.show-logs=true
quarkus.hibernate-orm.database.generation=update